export const curatedGenreMovies = {
  Action: [
    "Raiders of the Lost Ark",
    "Top Gun: Maverick",
    "Mission: Impossible",
    "The Incredibles",
    "Spider-Man: Into the Spider-Verse",
    "Guardians of the Galaxy",
    "The Avengers",
    "National Treasure",
    "Jumanji: Welcome to the Jungle",
    "The Karate Kid",
    "Pacific Rim",
    "The Mask of Zorro",
    "Free Guy",
    "Ant-Man",
    "Black Panther",
    "Wonder Woman",
    "The Rocketeer",
    "Speed Racer"
  ],
  Adventure: [
    "The Princess Bride",
    "The Goonies",
    "Jumanji",
    "Night at the Museum",
    "The Mummy",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "The Adventures of Tintin",
    "Holes",
    "Journey to the Center of the Earth",
    "The Secret Life of Walter Mitty",
    "The Jungle Book",
    "The NeverEnding Story",
    "The Swiss Family Robinson",
    "Paddington 2",
    "Hugo",
    "The Spiderwick Chronicles",
    "Zathura",
    "The Lost City"
  ],
  Animation: [
    "Toy Story",
    "Finding Nemo",
    "The Incredibles",
    "Ratatouille",
    "Wall-E",
    "Up",
    "Inside Out",
    "Coco",
    "Moana",
    "Encanto",
    "How to Train Your Dragon",
    "Shrek",
    "Kung Fu Panda",
    "The Lego Movie",
    "Spider-Man: Into the Spider-Verse",
    "Klaus",
    "The Iron Giant",
    "Kiki's Delivery Service"
  ],
  Comedy: [
    "The Princess Bride",
    "Groundhog Day",
    "School of Rock",
    "Elf",
    "The Parent Trap",
    "Father of the Bride",
    "Galaxy Quest",
    "The Lego Movie",
    "Paddington",
    "Paddington 2",
    "Night at the Museum",
    "The Muppets",
    "Freaky Friday",
    "Mrs. Doubtfire",
    "Napoleon Dynamite",
    "Ferris Bueller's Day Off",
    "The Sandlot",
    "The Intern"
  ],
  Drama: [
    "Hidden Figures",
    "Remember the Titans",
    "Akeelah and the Bee",
    "October Sky",
    "The Blind Side",
    "Little Women",
    "The Help",
    "Wonder",
    "The Pursuit of Happyness",
    "The Secret Life of Walter Mitty",
    "The Martian",
    "Julie & Julia",
    "Saving Mr. Banks",
    "The King's Speech",
    "The Truman Show",
    "Big Fish",
    "The Rookie",
    "Soul Surfer"
  ],
  Family: [
    "The Parent Trap",
    "Cheaper by the Dozen",
    "The Sandlot",
    "Home Alone",
    "Matilda",
    "Because of Winn-Dixie",
    "Akeelah and the Bee",
    "Wonder",
    "The Princess Diaries",
    "The Secret Garden",
    "Babe",
    "Stuart Little",
    "The Peanuts Movie",
    "Paddington",
    "Dolphin Tale",
    "Pete's Dragon",
    "The Game Plan",
    "Ramona and Beezus"
  ],
  Fantasy: [
    "The Princess Bride",
    "Harry Potter and the Sorcerer's Stone",
    "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    "Stardust",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Hobbit: An Unexpected Journey",
    "Howl's Moving Castle",
    "Kiki's Delivery Service",
    "Spirited Away",
    "The NeverEnding Story",
    "The Secret of NIMH",
    "The Spiderwick Chronicles",
    "Bridge to Terabithia",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "Labyrinth",
    "Willow",
    "The Dark Crystal",
    "Pete's Dragon"
  ],
  Mystery: [
    "Knives Out",
    "Enola Holmes",
    "Nancy Drew",
    "Clue",
    "National Treasure",
    "Hugo",
    "The Adventures of Tintin",
    "Sherlock Holmes",
    "The Kid Detective",
    "Holes",
    "Rear Window",
    "Murder on the Orient Express",
    "The Great Mouse Detective",
    "A Series of Unfortunate Events",
    "The Spiderwick Chronicles",
    "The Prestige",
    "Searching",
    "Missing"
  ],
  "Sci-Fi": [
    "Back to the Future",
    "The Martian",
    "Wall-E",
    "E.T. the Extra-Terrestrial",
    "Star Wars: Episode IV - A New Hope",
    "The Iron Giant",
    "Big Hero 6",
    "Treasure Planet",
    "Meet the Robinsons",
    "Zathura",
    "Tomorrowland",
    "Flight of the Navigator",
    "Galaxy Quest",
    "Interstellar",
    "Arrival",
    "The Mitchells vs. the Machines",
    "Lightyear",
    "Ready Player One"
  ]
};
